services:
  development:
    container_name: development
    build:
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

  production:
    container_name: production
    build: 
      target: production
    ports:
      - "${CLIENT_PORT:-3000}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    restart: always